BUILD_DIR = ./build

all: $(BUILD_DIR) $(BUILD_DIR)/OS_0005

$(BUILD_DIR):
	mkdir $(BUILD_DIR)

$(BUILD_DIR)/OS_0005: OS_0005.c
	gcc OS_0005.c -o $(BUILD_DIR)/OS_0005

OS_0005.c:
	echo "OS_0005 file does not exists"
