SRC_DIR := .
BUILD_DIR := ./build

all: $(BUILD_DIR) $(BUILD_DIR)/OS08_05

$(BUILD_DIR):
	mkdir $(BUILD_DIR)

$(BUILD_DIR)/OS08_05: $(SRC_DIR)/OS08_05.c
	gcc $(SRC_DIR)/OS08_05.c -o $(BUILD_DIR)/OS08_05
	
$(SRC_DIR)/OS08_05.c:
	echo "$(SRC_DIR)/OS08_05.c no such file"
