BUILD_DIR=./build
SRC_DIR=./

all: $(BUILD_DIR) $(BUILD_DIR)/OS07_06

$(BUILD_DIR):
	mkdir $(BUILD_DIR)

$(BUILD_DIR)/OS07_06: $(SRC_DIR)/OS07_06.c
	gcc $(SRC_DIR)/OS07_06.c -o $(BUILD_DIR)/OS07_06

$(SRC_DIR)/OS07_06.c:
	echo $(SRC_DIR)/OS07_06.c file does not exists
